### ISSUE TITLE
Versioning - tag v0.3.0 on GitHub and create v0.3.1?

### ISSUE THREAD

**Issue by jackwilsdon** [sampsyo/confit#20]
Would it be possible to tag 2d46b5f383033b5ea540e5ea424f395da1d40936 as `v0.3.0`, as well as to create a `v0.3.1` tag (and subsequent PyPI release) for confit?

I tried creating a PR for the `v0.3.0` tag but it turns out GitHub doesn't recognise tags as actual changes!

Thanks! 😄

**Comment by sampsyo** [comment]
Done! I also added you as a collaborator so you can make changes here too.

**Comment by jackwilsdon** [comment]
Thanks! Love the library, makes YAML much less painful 😆!
